/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/home/index" |
       "/pages/admin/index" |
       "/pages/auth/index" |
       "/pages/book-detail/index" |
       "/pages/borrow/index" |
       "/pages/favorites/index" |
       "/pages/feedback/index" |
       "/pages/profile/edit" |
       "/pages/profile/index" |
       "/pages/search/index" |
       "/pages-sub/demo/index" |
       "/pages-sub/page-admin/book-edit" |
       "/pages-sub/page-admin/book-manage" |
       "/pages-sub/page-admin/statistics";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/search/index" | "/pages/borrow/index" | "/pages/profile/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
